- name: "status:needs-triage"
  color: "FBCA04"
  description: "New issue or PR requires maintainer triage."
- name: "status:needs-info"
  color: "D4C5F9"
  description: "Reporter must provide missing diagnostics or reproduction details."
- name: "status:repro-ready"
  color: "C2E0C6"
  description: "Issue includes sufficient details for reproducible investigation."
- name: "status:confirmed"
  color: "0E8A16"
  description: "Maintainer has reproduced or validated the issue."
- name: "status:in-progress"
  color: "1D76DB"
  description: "A maintainer is actively implementing or validating a fix."
- name: "status:blocked"
  color: "B60205"
  description: "Work is blocked by dependency, environment, or external input."
- name: "status:ready-to-merge"
  color: "5319E7"
  description: "PR has required evidence and is waiting final merge decision."
- name: "status:done"
  color: "0E8A16"
  description: "Issue has been resolved and closed."

- name: "type:bug"
  color: "D73A4A"
  description: "Behavior does not match expected function."
- name: "type:enhancement"
  color: "A2EEEF"
  description: "Improvement to existing behavior or workflow."
- name: "type:security"
  color: "B60205"
  description: "Security behavior, hardening, or vulnerability concern."
- name: "type:docs"
  color: "0075CA"
  description: "Documentation updates or gaps."
- name: "type:question"
  color: "D876E3"
  description: "Clarification or support question."

- name: "area:installer-secrets"
  color: "F9D0C4"
  description: "Installer-first flow, startup contract, or runtime secrets."
- name: "area:compose-dev"
  color: "F9D0C4"
  description: "Development overlay compose behavior and local mounts."
- name: "area:compose-prod"
  color: "F9D0C4"
  description: "Production compose overlay behavior and runtime settings."
- name: "area:ui"
  color: "C5DEF5"
  description: "sirius-ui frontend and server-side API bridge."
- name: "area:api"
  color: "C5DEF5"
  description: "sirius-api routes, middleware, and API behavior."
- name: "area:engine"
  color: "C5DEF5"
  description: "sirius-engine scanning, gRPC, and orchestration behavior."
- name: "area:rabbitmq"
  color: "C5DEF5"
  description: "Queue durability, routing, and consumer behavior."
- name: "area:postgres"
  color: "C5DEF5"
  description: "Database schema, connection, and persistence concerns."
- name: "area:valkey"
  color: "C5DEF5"
  description: "Valkey cache/key lifecycle behavior."
- name: "area:auth"
  color: "C5DEF5"
  description: "Authentication, API key validation, and auth surfaces."

- name: "sev:critical"
  color: "B60205"
  description: "Security/data-loss/system integrity risk requiring immediate response."
- name: "sev:high"
  color: "D93F0B"
  description: "System unusable or major reliability break."
- name: "sev:medium"
  color: "FBCA04"
  description: "Substantial issue with workaround available."
- name: "sev:low"
  color: "0E8A16"
  description: "Minor issue or paper-cut with low immediate risk."

- name: "platform:windows"
  color: "BFDADC"
  description: "Issue specific to Windows/WSL2 environments."
