# AWS-specific Docker Compose override
# This file is designed for AWS deployment without volume mounts
# Usage: docker-compose -f docker-compose.yaml -f docker-compose.aws.yaml up -d

version: "3.8"

services:
  sirius-api:
    build:
      context: ./sirius-api/
      target: builder  # Use builder stage which includes the git clone
    environment:
      - GO_ENV=production
      - LOG_LEVEL=info
    # Remove volume mounts - use built-in git clone instead

  sirius-engine:
    build:
      context: ./sirius-engine/
      target: runtime  # Use production runtime stage
    environment:
      - GO_ENV=production
      - LOG_LEVEL=info
    # Remove volume mounts - use built-in repositories

  sirius-ui:
    environment:
      - NODE_ENV=production
      - SKIP_ENV_VALIDATION=1
      - DATABASE_URL=postgresql://postgres:postgres@sirius-postgres:5432/sirius
