# Production Docker Compose for AWS/Remote Deployment
# This file provides production-specific overrides for environment variables
# Usage: docker-compose -f docker-compose.yaml -f docker-compose.production.yaml up -d

version: "3.8"

services:
  sirius-ui:
    environment:
      - NODE_ENV=production
      - SKIP_ENV_VALIDATION=1
      # Use PostgreSQL in production instead of SQLite
      - DATABASE_URL=postgresql://postgres:postgres@sirius-postgres:5432/sirius
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-change-this-secret-in-production-please}
      - NEXTAUTH_URL=${NEXTAUTH_URL:-http://localhost:3000}
      - SIRIUS_API_URL=http://sirius-api:9001
      - NEXT_PUBLIC_SIRIUS_API_URL=${NEXT_PUBLIC_SIRIUS_API_URL:-http://localhost:9001}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID:-dummy_client_id}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET:-dummy_client_secret}

  sirius-api:
    environment:
      - GO_ENV=production
      - LOG_LEVEL=info

  sirius-engine:
    environment:
      - GO_ENV=production
      - LOG_LEVEL=info
