services:
  sirius-rabbitmq:
    build:
      context: ./sirius-rabbitmq
      dockerfile: Dockerfile
    image: sirius-sirius-rabbitmq:source
    pull_policy: never

  sirius-postgres:
    build:
      context: ./sirius-postgres
      dockerfile: Dockerfile
    image: sirius-sirius-postgres:source
    pull_policy: never

  sirius-valkey:
    build:
      context: ./sirius-valkey
      dockerfile: Dockerfile
    image: sirius-sirius-valkey:source
    pull_policy: never

  sirius-ui:
    build:
      context: ./sirius-ui
      dockerfile: Dockerfile
      target: production
    image: sirius-sirius-ui:source
    pull_policy: never

  sirius-api:
    build:
      context: ./sirius-api
      dockerfile: Dockerfile
      target: runner
    image: sirius-sirius-api:source
    pull_policy: never

  sirius-engine:
    build:
      context: ./sirius-engine
      dockerfile: Dockerfile
      target: runtime
    image: sirius-sirius-engine:source
    pull_policy: never
