/**
 * Extension contract compatibility harness (Phase 3.6).
 *
 * Proves, without any access to a private repository, that:
 *
 *   1. a Community build works with zero overlays;
 *   2. a synthetic extension compiles and composes through the public slots,
 *      enforces capabilities, and fails closed;
 *   3. a consumer written against the pinned v1 contract still type-checks.
 *
 * The overlay is applied the way a private build applies it: by replacing the
 * two registration modules only. Canonical files (auth.ts, trpc.ts, root.ts,
 * Sidebar.tsx, _app.tsx) are never touched, and the originals are restored even
 * when a check fails.
 */
import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

const projectRoot = path.resolve(__dirname, "..");
const CORE_CONTRACT_SHA = "823a80f663e585db775da4ce58b27ac0e5dcfbd2";

interface RegistrationModule {
  file: string;
  overlay: string;
}

const registrationModules: readonly RegistrationModule[] = [
  {
    file: "src/server/extensions/registered.ts",
    overlay:
      "// Applied by scripts/contract-harness.ts; restored when the harness exits.\n" +
      'export { syntheticServerExtensions as registeredServerExtensions } from "./harness/synthetic";\n',
  },
  {
    file: "src/server/extensions/registered-routers.ts",
    overlay:
      "// Applied by scripts/contract-harness.ts; restored when the harness exits.\n" +
      'export { syntheticServerRouters as registeredServerRouters } from "./harness/synthetic-routers";\n',
  },
];

const generatedInferenceFile =
  "src/server/extensions/harness/inference.generated.ts";

const generatedInference = `// Generated by scripts/contract-harness.ts while the synthetic overlay is
// applied. Proves the overlay's namespaces are inferred for clients rather than
// widened away by the registered-router spread.
import type { inferRouterInputs, inferRouterOutputs } from "@trpc/server";
import type { AppRouter } from "~/server/api/root";

type Outputs = inferRouterOutputs<AppRouter>;
type Inputs = inferRouterInputs<AppRouter>;
type IsAny<T> = 0 extends 1 & T ? true : false;
type AssertFalse<T extends false> = T;

type OverlayOutputNotAny = AssertFalse<IsAny<Outputs["syntheticWidgets"]["list"]>>;
type OverlayInputNotAny = AssertFalse<IsAny<Inputs["syntheticWidgetAdmin"]["rename"]>>;
type CommunityOutputNotAny = AssertFalse<IsAny<Outputs["host"]["getAllHosts"]>>;

const overlayResult: Outputs["syntheticWidgets"]["list"] = {
  subjectId: "subject:member",
  limit: 3,
};
const overlayProcedure: keyof Outputs["syntheticWidgetAdmin"] = "rename";
const communityProcedure: keyof Outputs["host"] = "getAllHosts";

export type { OverlayOutputNotAny, OverlayInputNotAny, CommunityOutputNotAny };
export { communityProcedure, overlayProcedure, overlayResult };
`;

function createThrowawayKeyFile(): string {
  const file = path.join(
    mkdtempSync(path.join(tmpdir(), "harness-")),
    "api-key",
  );
  writeFileSync(file, "contract-harness\n");
  return file;
}

// The harness imports the application router, which reads these at module load.
// A sqlite URL and a throwaway key file keep that import side-effect free.
const harnessEnv: NodeJS.ProcessEnv = {
  ...process.env,
  SKIP_ENV_VALIDATION: "1",
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET ?? "contract-harness",
  DATABASE_URL: process.env.DATABASE_URL ?? "file:./prisma/contract-harness.db",
  SIRIUS_API_KEY_FILE:
    process.env.SIRIUS_API_KEY_FILE ?? createThrowawayKeyFile(),
};

function read(file: string): string {
  return readFileSync(path.join(projectRoot, file), "utf8");
}

function write(file: string, contents: string): void {
  writeFileSync(path.join(projectRoot, file), contents);
}

function run(
  label: string,
  command: string,
  args: readonly string[],
): { status: number | null; stdout: string; stderr: string } {
  process.stdout.write(`\n[harness] ${label}\n`);
  const result = spawnSync(command, [...args], {
    cwd: projectRoot,
    env: harnessEnv,
    encoding: "utf8",
  });

  if (result.error) {
    throw result.error;
  }

  return {
    status: result.status,
    stdout: result.stdout ?? "",
    stderr: result.stderr ?? "",
  };
}

function runOrFail(
  label: string,
  command: string,
  args: readonly string[],
): void {
  const result = run(label, command, args);
  process.stdout.write(result.stdout);

  if (result.status !== 0) {
    process.stderr.write(result.stderr);
    throw new Error(`${label} failed with exit code ${String(result.status)}`);
  }
}

/**
 * Type-checks the project and fails only on errors in contract or harness
 * sources. The application carries pre-existing baseline errors elsewhere, so
 * scoping the assertion keeps the harness meaningful without pretending to fix
 * unrelated code.
 */
function typeCheckContractSources(): void {
  const result = run("type-checking contract sources", "npx", [
    "tsc",
    "--noEmit",
  ]);
  const ownErrors = result.stdout
    .split("\n")
    .filter(
      (line) =>
        /error TS/.test(line) &&
        /(src\/server\/extensions\/|src\/contracts\/)/.test(line),
    );

  if (ownErrors.length > 0) {
    throw new Error(
      `contract type check failed:\n${ownErrors.join("\n")}\n\n` +
        "A v1 consumer no longer compiles against the current contract. " +
        "Contract changes must be additive.",
    );
  }

  process.stdout.write("no contract type errors\n");
}

function main(): void {
  process.stdout.write(
    `[harness] extension contract harness against Core ${CORE_CONTRACT_SHA}\n`,
  );

  const originals = registrationModules.map(({ file }) => ({
    file,
    contents: read(file),
  }));

  for (const { contents } of originals) {
    if (/harness\//.test(contents)) {
      throw new Error(
        "a registration module already references the harness; refusing to run",
      );
    }
  }

  runOrFail("Community baseline with zero overlays", "npx", [
    "tsx",
    "src/server/extensions/harness/baseline.ts",
  ]);

  try {
    for (const { file, overlay } of registrationModules) {
      write(file, overlay);
    }
    write(generatedInferenceFile, generatedInference);

    typeCheckContractSources();
    runOrFail("synthetic overlay checks", "npx", [
      "tsx",
      "src/server/extensions/harness/checks.ts",
    ]);
  } finally {
    for (const { file, contents } of originals) {
      write(file, contents);
    }
    rmSync(path.join(projectRoot, generatedInferenceFile), { force: true });
  }

  process.stdout.write("\n[harness] extension contracts are compatible\n");
}

try {
  main();
} catch (cause) {
  process.stderr.write(`\n[harness] ${String(cause)}\n`);
  process.exit(1);
}
