name: Bug Report
description: Report a reproducible defect in Sirius Scan.
title: "[bug]: "
labels:
  - status:needs-triage
  - type:bug
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug. Please provide enough detail for maintainers to reproduce quickly.

  - type: input
    id: component
    attributes:
      label: Affected Component
      placeholder: "e.g. sirius-api, sirius-ui, scanner workflow, docker startup"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "e.g. v1.0.0, main, commit SHA"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Logs and Evidence
      description: Include command output, screenshots, and relevant logs.
    validations:
      required: true
