id: "SSH-CONFIG-001"
info:
  name: "SSH Weak Configuration Detection"
  author: "sirius-team"
  severity: "medium"
  description: "Detects weak SSH configuration settings that may lead to security vulnerabilities"
  references:
    - "https://www.ssh.com/academy/ssh/sshd_config"
    - "https://linux.die.net/man/5/sshd_config"
  cve: "CUSTOM-SSH-001"
  created: "2024-01-15T10:30:00Z"
  updated: "2024-01-15T10:30:00Z"

detection:
  type: "config-file"
  files:
    - path: "/etc/ssh/sshd_config"
      patterns:
        - regex: "^\\s*PermitRootLogin\\s+yes"
          description: "Root login permitted via SSH"
          severity: "high"
        - regex: "^\\s*PasswordAuthentication\\s+yes"
          description: "Password authentication enabled"
          severity: "medium"
        - regex: "^\\s*PermitEmptyPasswords\\s+yes"
          description: "Empty passwords permitted"
          severity: "critical"
        - regex: "^\\s*Protocol\\s+1"
          description: "SSH Protocol 1 enabled (deprecated)"
          severity: "high"
        - regex: "^\\s*X11Forwarding\\s+yes"
          description: "X11 forwarding enabled (potential risk)"
          severity: "low"

  conditions:
    - type: "file_exists"
      value: true
    - type: "pattern_found"
      value: true

  metadata:
    confidence: 0.85
    impact: "Unauthorized access, privilege escalation"
    affected_services: ["sshd", "ssh"]

remediation:
  description: "Review and harden SSH configuration settings"
  commands:
    linux: |
      # Edit /etc/ssh/sshd_config and apply these settings:
      # PermitRootLogin no
      # PasswordAuthentication no
      # PermitEmptyPasswords no
      # Protocol 2
      # X11Forwarding no
      sudo systemctl restart sshd
  verification:
    command: "sshd -T | grep -E '(permitrootlogin|passwordauthentication|permitemptypasswords)'"
    expected_pattern: "permitrootlogin no.*passwordauthentication no.*permitemptypasswords no"
